import Link from "next/link";

export const metadata = {
  title: "Terms of Service — MarkReady",
};

const EFFECTIVE_DATE = "July 14, 2026";

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-[#FAF8F3]">
      <header className="border-b border-[#E4DFD3] bg-[#FAF8F3]/80 backdrop-blur sticky top-0 z-20">
        <div className="max-w-3xl mx-auto px-4 py-4 flex items-center justify-between">
          <Link href="/" className="font-serif text-xl font-semibold text-[#23282B]">
            MarkReady
          </Link>
          <Link href="/login" className="text-sm text-[#1F5C4E] hover:text-[#154136]">
            Sign in
          </Link>
        </div>
      </header>

      <main className="max-w-3xl mx-auto px-4 py-10">
        <h1 className="font-serif text-3xl font-semibold text-[#23282B] mb-2">
          Terms of Service
        </h1>
        <p className="text-sm text-[#5B6266] mb-8">Effective date: {EFFECTIVE_DATE}</p>

        <div className="space-y-8 text-[#23282B] text-[15px] leading-relaxed">
          <section>
            <h2 className="font-serif text-xl font-semibold mb-2">1. About MarkReady</h2>
            <p>
              MarkReady is a practice tool that uses artificial intelligence to give feedback
              on English writing tasks, including estimated band scores in the style of the
              IELTS writing assessment. By creating an account or using the service, you
              agree to these terms. If you do not agree, please do not use MarkReady.
            </p>
          </section>

          <section>
            <h2 className="font-serif text-xl font-semibold mb-2">
              2. AI-generated estimates — not official scores
            </h2>
            <p>
              All scores, band estimates, and feedback produced by MarkReady are generated by
              AI language models. They are <strong>estimates intended to guide your
              practice</strong>. They are not official results, do not predict your official
              score, and may contain errors. An official examiner may score the same piece of
              writing differently. Do not rely on MarkReady output for admissions,
              immigration, employment, or any other formal purpose.
            </p>
          </section>

          <section>
            <h2 className="font-serif text-xl font-semibold mb-2">3. Trademark notice</h2>
            <p>
              IELTS™ is a registered trademark of the British Council, IDP: IELTS Australia,
              and Cambridge University Press &amp; Assessment. <strong>MarkReady is an
              independent study tool and is not affiliated with, endorsed by, or connected to
              the British Council, IDP: IELTS Australia, Cambridge University Press &amp;
              Assessment, or any official examination body.</strong> References to IELTS are
              made solely to describe the style of writing tasks the tool helps you practise.
            </p>
          </section>

          <section>
            <h2 className="font-serif text-xl font-semibold mb-2">4. Your account</h2>
            <p>
              You must provide accurate information when creating an account and keep your
              login credentials secure. You are responsible for activity that happens under
              your account. You must be at least 16 years old (or the minimum age required in
              your country) to use MarkReady.
            </p>
          </section>

          <section>
            <h2 className="font-serif text-xl font-semibold mb-2">5. Fair use and limits</h2>
            <p>
              The service currently allows a limited number of evaluations per day per
              account. You agree not to circumvent these limits (for example, by creating
              multiple accounts), not to use the service in an automated or abusive way, and
              not to submit content that is unlawful or that you do not have the right to
              submit. We may suspend or terminate accounts that violate these terms.
            </p>
          </section>

          <section>
            <h2 className="font-serif text-xl font-semibold mb-2">6. Your content</h2>
            <p>
              You keep ownership of the writing you submit. By submitting it, you give us
              permission to process and store it in order to provide the service — including
              sending your text to third-party AI model providers for scoring and storing
              your results so you can track your progress. See the{" "}
              <Link href="/privacy" className="text-[#1F5C4E] underline hover:text-[#154136]">
                Privacy Policy
              </Link>{" "}
              for details on how your data is handled.
            </p>
          </section>

          <section>
            <h2 className="font-serif text-xl font-semibold mb-2">7. Service availability</h2>
            <p>
              MarkReady is provided &ldquo;as is&rdquo; and &ldquo;as available,&rdquo;
              without warranties of any kind. The service is in active development: features
              may change, and the service may be interrupted or discontinued at any time
              without notice.
            </p>
          </section>

          <section>
            <h2 className="font-serif text-xl font-semibold mb-2">8. Limitation of liability</h2>
            <p>
              To the maximum extent permitted by law, MarkReady and its operators are not
              liable for any indirect, incidental, or consequential damages arising from your
              use of the service — including decisions made in reliance on AI-generated
              scores or feedback.
            </p>
          </section>

          <section>
            <h2 className="font-serif text-xl font-semibold mb-2">9. Changes to these terms</h2>
            <p>
              We may update these terms from time to time. Material changes will be reflected
              by updating the effective date above. Continuing to use the service after a
              change means you accept the updated terms.
            </p>
          </section>

          <section>
            <h2 className="font-serif text-xl font-semibold mb-2">10. Contact</h2>
            <p>
              Questions about these terms? Use the feedback link inside the app after signing
              in.
            </p>
          </section>
        </div>

        <footer className="mt-12 pt-6 border-t border-[#E4DFD3] text-sm text-[#5B6266] flex gap-4">
          <Link href="/privacy" className="hover:text-[#23282B] underline">
            Privacy Policy
          </Link>
          <Link href="/login" className="hover:text-[#23282B] underline">
            Sign in
          </Link>
        </footer>
      </main>
    </div>
  );
}
